---
# handlers file for vsftpd

- name: run restorecon
  command: restorecon -v /var/ftp/pub
- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted
- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
