---
# defaults file for vsftpd

    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes
    services:
      - vsftpd
      - firewalld
    packages:
      - vsftpd
      - firewalld
      - policycoreutils-python-utils
    fileperms:
      - /var/ftp/pub
      - /var/ftp/pub/upload